[2024-02-26T08:57:08.733+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T08:56:52.846887+00:00 [queued]>
[2024-02-26T08:57:08.746+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T08:56:52.846887+00:00 [queued]>
[2024-02-26T08:57:08.747+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T08:57:08.958+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_exchange_data> on 2024-02-26 08:56:52.846887+00:00
[2024-02-26T08:57:08.966+0000] {standard_task_runner.py:60} INFO - Started process 8591 to run task
[2024-02-26T08:57:08.971+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'transform_exchange_data', 'manual__2024-02-26T08:56:52.846887+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpdp9r85co']
[2024-02-26T08:57:08.972+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask transform_exchange_data
[2024-02-26T08:57:09.036+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T08:56:52.846887+00:00 [running]> on host f5283f9a0a92
[2024-02-26T08:57:09.159+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='transform_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T08:56:52.846887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T08:56:52.846887+00:00'
[2024-02-26T08:57:09.161+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 45, in transform_exchange_data
    for result in results:
TypeError: 'NoneType' object is not iterable
[2024-02-26T08:57:09.171+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=transform_exchange_data, execution_date=20240226T085652, start_date=20240226T085708, end_date=20240226T085709
[2024-02-26T08:57:09.192+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task transform_exchange_data ('NoneType' object is not iterable; 8591)
[2024-02-26T08:57:09.223+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T08:57:09.250+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
