[2024-02-26T06:29:24.534+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data scheduled__2024-02-25T17:02:00+00:00 [queued]>
[2024-02-26T06:29:24.902+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data scheduled__2024-02-25T17:02:00+00:00 [queued]>
[2024-02-26T06:29:24.903+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T06:29:27.213+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_exchange_data> on 2024-02-25 17:02:00+00:00
[2024-02-26T06:29:27.247+0000] {standard_task_runner.py:60} INFO - Started process 2303 to run task
[2024-02-26T06:29:27.277+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'transform_exchange_data', 'scheduled__2024-02-25T17:02:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmp703vu6vx']
[2024-02-26T06:29:27.292+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask transform_exchange_data
[2024-02-26T06:29:28.305+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.transform_exchange_data scheduled__2024-02-25T17:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-26T06:29:30.161+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='transform_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T17:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-25T17:02:00+00:00'
[2024-02-26T06:29:30.224+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 50, in transform_exchange_data
    for result in results:
TypeError: 'NoneType' object is not iterable
[2024-02-26T06:29:29.072+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=transform_exchange_data, execution_date=20240225T170200, start_date=20240226T062924, end_date=20240226T062929
[2024-02-26T06:29:29.251+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task transform_exchange_data ('NoneType' object is not iterable; 2303)
[2024-02-26T06:29:29.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T06:29:29.666+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
