[2024-03-02T03:17:02.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data scheduled__2024-03-02T02:10:00+00:00 [queued]>
[2024-03-02T03:17:02.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data scheduled__2024-03-02T02:10:00+00:00 [queued]>
[2024-03-02T03:17:02.731+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-02T03:17:02.967+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2024-03-02 02:10:00+00:00
[2024-03-02T03:17:03.003+0000] {standard_task_runner.py:60} INFO - Started process 1936 to run task
[2024-03-02T03:17:03.090+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'load_data', 'scheduled__2024-03-02T02:10:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ecom.py', '--cfg-path', '/tmp/tmpiporx4ns']
[2024-03-02T03:17:03.106+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask load_data
[2024-03-02T03:17:03.195+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-02T03:17:03.418+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_pipeline.load_data scheduled__2024-03-02T02:10:00+00:00 [running]> on host 70b88be0f8e4
[2024-03-02T03:17:05.474+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-02T02:10:00+00:00'
[2024-03-02T03:17:05.530+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ecommerce.py", line 72, in load_data
    db_data.to_sql(name=table_name, con=con, if_exists="replace", index=False)
AttributeError: 'str' object has no attribute 'to_sql'
[2024-03-02T03:17:05.644+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ecommerce_pipeline, task_id=load_data, execution_date=20240302T021000, start_date=20240302T031702, end_date=20240302T031705
[2024-03-02T03:17:05.746+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task load_data ('str' object has no attribute 'to_sql'; 1936)
[2024-03-02T03:17:05.795+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-02T03:17:05.853+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
