[2024-02-26T21:19:54.174+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-26T20:01:00+00:00 [queued]>
[2024-02-26T21:19:54.344+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-26T20:01:00+00:00 [queued]>
[2024-02-26T21:19:54.345+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T21:19:54.695+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): get_exchange_data> on 2024-02-26 20:01:00+00:00
[2024-02-26T21:19:54.742+0000] {standard_task_runner.py:60} INFO - Started process 16403 to run task
[2024-02-26T21:19:54.807+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'get_exchange_data', 'scheduled__2024-02-26T20:01:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmp0n1v7ij8']
[2024-02-26T21:19:54.822+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask get_exchange_data
[2024-02-26T21:19:55.049+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-26T21:19:55.572+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-26T20:01:00+00:00 [running]> on host e16193345271
[2024-02-26T21:19:57.924+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='get_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T20:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T20:01:00+00:00'
[2024-02-26T21:20:22.553+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-26T21:20:22.806+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=exchange_trade_data, task_id=get_exchange_data, execution_date=20240226T200100, start_date=20240226T211954, end_date=20240226T212022
[2024-02-27T05:41:28.252+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2024-02-27T05:41:28.255+0000] {process_utils.py:131} INFO - Sending 15 to group 16403. PIDs of all processes in the group: [16403]
[2024-02-27T05:41:28.255+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 16403
[2024-02-27T05:41:31.068+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-27T05:41:31.105+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task get_exchange_data (Task received SIGTERM signal; 16403)
[2024-02-27T05:41:31.377+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=16403, status='terminated', exitcode=1, started='21:19:54') (16403) terminated with exit code 1
