[2024-03-02T03:17:02.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T02:10:00+00:00 [queued]>
[2024-03-02T03:17:02.967+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T02:10:00+00:00 [queued]>
[2024-03-02T03:17:02.995+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-02T03:17:03.193+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): clean_customers> on 2024-03-02 02:10:00+00:00
[2024-03-02T03:17:03.208+0000] {standard_task_runner.py:60} INFO - Started process 1937 to run task
[2024-03-02T03:17:03.276+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'clean_customers', 'scheduled__2024-03-02T02:10:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/ecom.py', '--cfg-path', '/tmp/tmpmq1dnwp2']
[2024-03-02T03:17:03.286+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask clean_customers
[2024-03-02T03:17:03.406+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-02T03:17:03.755+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T02:10:00+00:00 [running]> on host 70b88be0f8e4
[2024-03-02T03:17:05.898+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='clean_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T02:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-02T02:10:00+00:00'
[2024-03-02T03:17:05.902+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ecommerce.py", line 30, in clean_data
    data = df_data.drop_duplicates()
AttributeError: 'str' object has no attribute 'drop_duplicates'
[2024-03-02T03:17:05.938+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ecommerce_pipeline, task_id=clean_customers, execution_date=20240302T021000, start_date=20240302T031702, end_date=20240302T031705
[2024-03-02T03:17:05.995+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task clean_customers ('str' object has no attribute 'drop_duplicates'; 1937)
[2024-03-02T03:17:06.063+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-02T03:17:06.139+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
