[2024-03-02T03:16:36.753+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T00:01:00+00:00 [queued]>
[2024-03-02T03:16:36.824+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T00:01:00+00:00 [queued]>
[2024-03-02T03:16:36.825+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-02T03:16:36.923+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): clean_customers> on 2024-03-02 00:01:00+00:00
[2024-03-02T03:16:36.958+0000] {standard_task_runner.py:60} INFO - Started process 1793 to run task
[2024-03-02T03:16:37.063+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'clean_customers', 'scheduled__2024-03-02T00:01:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/ecom.py', '--cfg-path', '/tmp/tmpk1910ul0']
[2024-03-02T03:16:37.067+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask clean_customers
[2024-03-02T03:16:37.261+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-02T03:16:37.786+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_pipeline.clean_customers scheduled__2024-03-02T00:01:00+00:00 [running]> on host 70b88be0f8e4
[2024-03-02T03:16:42.072+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='clean_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-02T00:01:00+00:00'
[2024-03-02T03:16:42.089+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ecommerce.py", line 30, in clean_data
    data = df_data.drop_duplicates()
AttributeError: 'str' object has no attribute 'drop_duplicates'
[2024-03-02T03:16:42.258+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ecommerce_pipeline, task_id=clean_customers, execution_date=20240302T000100, start_date=20240302T031636, end_date=20240302T031642
[2024-03-02T03:16:42.501+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task clean_customers ('str' object has no attribute 'drop_duplicates'; 1793)
[2024-03-02T03:16:42.655+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-02T03:16:42.734+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
