[2024-02-26T08:34:45.781+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md manual__2024-02-26T08:34:40.042664+00:00 [queued]>
[2024-02-26T08:34:45.831+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.connect_to_md manual__2024-02-26T08:34:40.042664+00:00 [queued]>
[2024-02-26T08:34:45.832+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T08:34:46.506+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): connect_to_md> on 2024-02-26 08:34:40.042664+00:00
[2024-02-26T08:34:46.516+0000] {standard_task_runner.py:60} INFO - Started process 7215 to run task
[2024-02-26T08:34:46.522+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'connect_to_md', 'manual__2024-02-26T08:34:40.042664+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpbhqksimh']
[2024-02-26T08:34:46.527+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask connect_to_md
[2024-02-26T08:34:46.621+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.connect_to_md manual__2024-02-26T08:34:40.042664+00:00 [running]> on host f5283f9a0a92
[2024-02-26T08:34:46.879+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='connect_to_md' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T08:34:40.042664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T08:34:40.042664+00:00'
[2024-02-26T08:34:51.168+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 84, in connect_to_md
    con = db.connect(f'md:{database_name}?motherduck_token={motherduck_token}')
duckdb.duckdb.InvalidInputException: Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.17.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818de48d-6fcb-4cf1-8b8c-52ce073d59fc')""
[2024-02-26T08:34:51.197+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=connect_to_md, execution_date=20240226T083440, start_date=20240226T083445, end_date=20240226T083451
[2024-02-26T08:34:51.271+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task connect_to_md (Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/home/***/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/motherduck.v1.15.17.duckdb_extension" threw an exception: "IO Error: RPC 'GET_WELCOME_PACK' failed: Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections (UNAUTHENTICATED, request id: '818de48d-6fcb-4cf1-8b8c-52ce073d59fc')""; 7215)
[2024-02-26T08:34:51.339+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T08:34:51.426+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
