[2024-02-26T17:59:52.249+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T17:59:35.517113+00:00 [queued]>
[2024-02-26T17:59:52.268+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T17:59:35.517113+00:00 [queued]>
[2024-02-26T17:59:52.268+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T17:59:52.296+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_exchange_data> on 2024-02-26 17:59:35.517113+00:00
[2024-02-26T17:59:52.303+0000] {standard_task_runner.py:60} INFO - Started process 13925 to run task
[2024-02-26T17:59:52.307+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'transform_exchange_data', 'manual__2024-02-26T17:59:35.517113+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmph8qguq0e']
[2024-02-26T17:59:52.309+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask transform_exchange_data
[2024-02-26T17:59:52.340+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-26T17:59:52.404+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-02-26T17:59:35.517113+00:00 [running]> on host e16193345271
[2024-02-26T17:59:52.981+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='transform_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T17:59:35.517113+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T17:59:35.517113+00:00'
[2024-02-26T17:59:52.993+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 48, in transform_exchange_data
    for result in results:
TypeError: 'NoneType' object is not iterable
[2024-02-26T17:59:53.008+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=transform_exchange_data, execution_date=20240226T175935, start_date=20240226T175952, end_date=20240226T175953
[2024-02-26T17:59:53.040+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task transform_exchange_data ('NoneType' object is not iterable; 13925)
[2024-02-26T17:59:53.061+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T17:59:53.332+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
