[2024-03-01T15:21:36.259+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-03-01T15:21:20.031768+00:00 [queued]>
[2024-03-01T15:21:36.273+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-03-01T15:21:20.031768+00:00 [queued]>
[2024-03-01T15:21:36.273+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-01T15:21:36.465+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_exchange_data> on 2024-03-01 15:21:20.031768+00:00
[2024-03-01T15:21:36.473+0000] {standard_task_runner.py:60} INFO - Started process 3582 to run task
[2024-03-01T15:21:36.478+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'transform_exchange_data', 'manual__2024-03-01T15:21:20.031768+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmp1i4667pu']
[2024-03-01T15:21:36.482+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask transform_exchange_data
[2024-03-01T15:21:36.554+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.transform_exchange_data manual__2024-03-01T15:21:20.031768+00:00 [running]> on host 11bab81981d3
[2024-03-01T15:21:36.718+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='transform_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T15:21:20.031768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-01T15:21:20.031768+00:00'
[2024-03-01T15:21:36.722+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange.py", line 48, in transform_exchange_data
    for result in results:
TypeError: 'NoneType' object is not iterable
[2024-03-01T15:21:36.744+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=exchange_trade_data, task_id=transform_exchange_data, execution_date=20240301T152120, start_date=20240301T152136, end_date=20240301T152136
[2024-03-01T15:21:36.767+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task transform_exchange_data ('NoneType' object is not iterable; 3582)
[2024-03-01T15:21:36.811+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-01T15:21:36.879+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
