[2024-02-25T20:25:40.410+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T17:02:00+00:00 [queued]>
[2024-02-25T20:25:40.506+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T17:02:00+00:00 [queued]>
[2024-02-25T20:25:40.507+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-25T20:25:41.745+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): get_exchange_data> on 2024-02-25 17:02:00+00:00
[2024-02-25T20:25:41.785+0000] {standard_task_runner.py:60} INFO - Started process 2276 to run task
[2024-02-25T20:25:41.857+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_trade_data', 'get_exchange_data', 'scheduled__2024-02-25T17:02:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/exchange.py', '--cfg-path', '/tmp/tmpqd5rk_s9']
[2024-02-25T20:25:41.873+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask get_exchange_data
[2024-02-25T20:25:42.247+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_trade_data.get_exchange_data scheduled__2024-02-25T17:02:00+00:00 [running]> on host f5283f9a0a92
[2024-02-25T20:25:42.930+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_trade_data' AIRFLOW_CTX_TASK_ID='get_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T17:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-25T17:02:00+00:00'
[2024-02-25T20:26:03.592+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-25T20:26:03.907+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=exchange_trade_data, task_id=get_exchange_data, execution_date=20240225T170200, start_date=20240225T202540, end_date=20240225T202603
[2024-02-26T06:29:03.511+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
